What is Numpy ?

1) Numpy is the fundamental package for scientific computing in python.

2)Numpy is a python library that provides a multidimensional array objects, various derived objects.

It is widely used in data science, machine learning, AI, image processing,


Key Features of NumPy:

1->N-dimensional array object called ndarray

2->Broadcasting functions (operate on arrays of different shapes)

3->Vectorized operations (fast performance using C backend)

4->Linear algebra, Fourier transform, and random number generation

What is Numpy Array ?

-> An array is a grid of values and it contains information about the raw data , how to locate an element, and how to interpret the element.

Advantage Of Numpy Array ?

1)consume less memory.

2)fast as compared to the python list.

list : [1 ,2, 3 ]  comma seprated values.

Array : [ 1 2 3]  not comma seperated values.

*Installation of numpy

pip install numpy


In [ ]:
# import numpy

import numpy as np

In [ ]:
# creating numpy array

x = np.array([1,2,3,4,5])
print(x)

# check datatype of variable
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# creating list

y =[1,2,3,4]
print(y)

# check datatype of variable
print(type(y))

[1, 2, 3, 4]
<class 'list'>


finding the running time using the functions

1) %timeit  -> it gives single line running time.

2)%%timeit -> it gives whole program running time.

In [ ]:
%timeit [ j ** 4 for j in range(1,9)]

1.1 µs ± 291 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
%timeit np.arange(1,9)**4

2.49 µs ± 1.03 µs per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


np.arange() is a function used to create arrays with regularly spaced values within a given range.

🔸 Syntax:

numpy.arange([start, ]stop, [step, ]dtype=None)

start (optional): Starting value of the sequence (default is 0)

stop (required): End value (not included)

step (optional): Spacing between values (default is 1)

dtype (optional): Desired data type



In [ ]:
import numpy as np

arr = np.arange(10)
print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:

arr = np.arange(2, 10)
print(arr)


[2 3 4 5 6 7 8 9]


In [ ]:
arr = np.arange(1, 10, 2)
print(arr)


[1 3 5 7 9]


Creating Array :



In [ ]:
x = [1,2,3,4,5]
y = np.array(x) # creating array using array() function.
print(y)
print(type(y))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:

l = []
for i in range(1, 5):
    int_1 = int(input("enter elements : "))
    l.append(int_1)
print("List : ",l)
print("Array : ",np.array(l))

enter elements : 10
enter elements : 20
enter elements : 30
enter elements : 40
List :  [10, 20, 30, 40]
Array :  [10 20 30 40]


Types Of Array :

1) 1D arrays

2) 2D arrays

3) 3D arrays

4) Higher Dimension Arrays

In [ ]:
# 1D array
import numpy as np

x = np.array([1,2,3,4,5])
print(x)

print(x.ndim) # checking dimension of array

[1 2 3 4 5]
1


In [ ]:
#2D array

y = np.array([[1,2,3],[4,5,6]])
print(y)

print(y.ndim)  # checking dimension of array

[[1 2 3]
 [4 5 6]]
2


In [ ]:
#3D array

z = np.array([[[1,2,3,4],[1 ,2,3,4],[1,2,3,4]]])

print(z)

print(z.ndim) # checking dimension of array

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [ ]:
#creating multi-dimensional array using the ndmin = dimensional value


arr = np.array([1,2,3,4,5], ndmin=10)  #creating 10 dimensional array

print(arr)

print(arr.ndim)


[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
10


Creating the special types of arrays filled with specific values.

zeros() function

In [ ]:
#Array filled with 0's
arr_zeros = np.zeros(4)
arr_zeros = arr_zeros.astype(int) # convert particular datatype integer , by default give floating values 0. like
print(arr_zeros)
print()
#zeros((rowscount , colcount))
arr_zeros1 = np.zeros((2,3))
print(arr_zeros1)
print(arr_zeros1.ndim)

[0 0 0 0]

[[0. 0. 0.]
 [0. 0. 0.]]
2


ones() function

In [ ]:
#Array filled with 1's

arr_ones = np.ones(4)
print(arr_ones)

print()
# 2x3 array filled with ones
arr_one = np.ones((2, 3))
print(arr_one)
print(arr_one.ndim)

[1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]]
2


Creating empty array

In [ ]:
arr_empty = np.empty(4)
print(arr_empty) # previous memory data comes in empty array.

[1. 1. 1. 1.]


Array diagonal element filled with 1's = identity matrix

eye() function

In [ ]:
arr_diagonal = np.eye(3)
print(arr_diagonal)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr_diagonal = np.eye(3,5)
print(arr_diagonal)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


linespace() function


In [ ]:
ar_line = np.linspace(0,10,num=5)
print(ar_line)

[ 0.   2.5  5.   7.5 10. ]


Creating numpy arrays with random numbers :

rand() -> generate values between 0 to 1





In [ ]:
#rand() function
random_array = np.random.rand(4)
print(random_array)


[0.33235169 0.22891567 0.40798316 0.14283316]


In [ ]:
rand_arr = np.random.rand(2,4)
print(rand_arr)

[[0.02616559 0.06869339 0.29826268 0.01799996]
 [0.62482077 0.16957858 0.31189476 0.56202344]]


randn() -> it generates the random values close to zero. this may be return positve or negative values as well.


In [ ]:
#randn() function

arr = np.random.randn(4)
print(arr)

[-0.04872097  0.11211936  1.82066016 -0.979795  ]


In [ ]:
arr = np.random.randn(4,3)
print(arr)

[[ 0.33331691 -0.37667925 -0.0856741 ]
 [-0.5635617   1.17442766  1.7598102 ]
 [ 2.05677329  0.89628717 -1.07881473]
 [ 0.27031499 -1.05832068 -0.59772009]]


🔹 np.random.ranf()

✅ Generates random float numbers between 0 and 1 (excluding 1).


In [ ]:
import numpy as np

arr = np.random.ranf(5)  # Generate 5 random floats
print(arr)

print()

arr = np.random.ranf((5,7))  # Generate 5 random floats
print(arr)
print(arr.ndim)

# print the size and shape of the array
print(arr.size)
print(arr.shape)

[0.07055976 0.76010166 0.7635824  0.76906988 0.06747651]

[[0.945745   0.53134283 0.98473319 0.40250249 0.84577625 0.24631838
  0.09926293]
 [0.90694312 0.78612855 0.6081365  0.56944143 0.82102835 0.20005133
  0.19386834]
 [0.91334632 0.25336749 0.05773153 0.76976619 0.24912622 0.37178916
  0.38475186]
 [0.57804218 0.19868765 0.84519414 0.6848973  0.07120051 0.55302672
  0.93980739]
 [0.09914624 0.43816349 0.04447324 0.09058948 0.75368958 0.21852975
  0.95205071]]
2
35
(5, 7)


randint() function

syntax : random.randint(start , end , elements/(shape), dtype)

In [ ]:
arr = np.random.randint(5,20,5)
print(arr)

[14 19 12  7 11]


#**Numpy Array Data Types**

| NumPy `dtype` | Description                      | Example               |
|---------------|----------------------------------|------------------------|
| `int8`        | 8-bit signed integer             | -128 to 127           |
| `int16`       | 16-bit signed integer            | -32,768 to 32,767     |
| `int32`       | 32-bit signed integer            | Default on 32-bit systems |
| `int64`       | 64-bit signed integer            | Default on 64-bit systems |
| `uint8`       | 8-bit unsigned integer           | 0 to 255              |
| `float16`     | 16-bit half-precision float      | Less common           |
| `float32`     | 32-bit single-precision float    | e.g., 3.14            |
| `float64`     | 64-bit double-precision float    | Default for float     |
| `complex64`   | Complex number (2×float32)       | e.g., 1.0 + 2.0j      |
| `complex128`  | Complex number (2×float64)       | High precision        |
| `bool_`       | Boolean                          | `True`, `False`       |
| `str_`        | Fixed-length Unicode string      | `"hello"`             |
| `object_`     | Generic Python objects           | Mixed types           |


In [ ]:
arr = np.array([1, 2, 3])
print(arr.dtype) # checking the type of data

print()

arr = np.array([1, 2, 3], dtype=np.float32)
print(arr)
print(arr.dtype)

int64

[1. 2. 3.]
float32


In [ ]:
arr = np.array([1.2, 2.5, 3.7])
int_arr = arr.astype(int) # converting one data type to another datatype
print(int_arr)

[1 2 3]


In [ ]:
arr = np.array([1, 2, 3])
str_arr = arr.astype(str)
print(str_arr)
print(str_arr.dtype)

['1' '2' '3']
<U21


In [ ]:
arr = np.array(['1', '2', '3'])
int_arr = np.int32(arr) #another way to converting data type
print(int_arr)
print(int_arr.dtype)

[1 2 3]
int32


In [ ]:
mix_arr = np.array([1, 2.5, '3'])
print(mix_arr)
print(mix_arr.dtype)

['1' '2.5' '3']
<U32


In [ ]:
alphabet_arr = np.array(['a', 'b', 'c'])
print(alphabet_arr)
print(alphabet_arr.dtype)

['a' 'b' 'c']
<U1


In [ ]:
alpha_num_arr = np.array(['a', 1, 'b', 2, 'c'])
print(alpha_num_arr)
print(alpha_num_arr.dtype)

['a' '1' 'b' '2' 'c']
<U21


✅ NumPy Data Types: Short Symbols Table

| Symbol | NumPy `dtype` | Description                        |
|--------|---------------|------------------------------------|
| `i1`   | `int8`        | 8-bit signed integer               |
| `i2`   | `int16`       | 16-bit signed integer              |
| `i4`   | `int32`       | 32-bit signed integer              |
| `i8`   | `int64`       | 64-bit signed integer              |
| `u1`   | `uint8`       | 8-bit unsigned integer             |
| `u2`   | `uint16`      | 16-bit unsigned integer            |
| `u4`   | `uint32`      | 32-bit unsigned integer            |
| `u8`   | `uint64`      | 64-bit unsigned integer            |
| `f2`   | `float16`     | 16-bit floating-point              |
| `f4`   | `float32`     | 32-bit floating-point              |
| `f8`   | `float64`     | 64-bit floating-point              |
| `c8`   | `complex64`   | 64-bit complex number (2 × f4)     |
| `c16`  | `complex128`  | 128-bit complex number (2 × f8)    |
| `b`    | `bool_`       | Boolean (`True` or `False`)        |
| `S`    | `bytes_`      | Fixed-length ASCII string          |
| `U`    | `str_`        | Fixed-length Unicode string        |
| `O`    | `object_`     | Python object (mixed types)        |


In [ ]:
arr = np.array([1, 2, 3], dtype='i1')
print(arr)
print(arr.dtype)

[1 2 3]
int8


In [ ]:
str_arr = np.array(['hello', 'world'], dtype='U')
print(str_arr)
print(str_arr.dtype)

['hello' 'world']
<U5


#Shape and Reshape in numpy arrays


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape : " ,arr.shape)  # Output: (2, 3)
print()
print("Size Of Array  : ",arr.size)

Shape :  (2, 3)

Size Of Array  :  6


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(2, 3)
print(new_arr)
print()
print(new_arr.ndim)
print()
print(new_arr.shape)
print()
print(new_arr.size)


[[1 2 3]
 [4 5 6]]

2

(2, 3)

6


In [ ]:
var = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], ndmin = 5)
print(var)
print()
print(var.ndim)
print()
print(var.shape)
print()
print(var.size)
print()

#reshape(row_number , col_number , elements_count_per_row )
new_var = var.reshape(2, 3, 2)
print(new_var)
print()
print(new_var.ndim)
print()
print(new_var.shape)
print()
print(new_var.size)

print()
#convert array into one dimension
print(new_var.reshape(-1))

[[[[[ 1  2  3  4  5  6  7  8  9 10 11 12]]]]]

5

(1, 1, 1, 1, 12)

12

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

3

(2, 3, 2)

12

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# Airthmetic Operation in Numpy Arrays

| Operation         | Symbol | NumPy Function         | Example (`a=[10,20,30]`, `b=[1,2,3]`) | Output         |
|------------------|--------|------------------------|---------------------------------------|----------------|
| Addition         | `+`    | `np.add(a, b)`         | `a + b`                               | `[11 22 33]`   |
| Subtraction      | `-`    | `np.subtract(a, b)`    | `a - b`                               | `[9 18 27]`    |
| Multiplication   | `*`    | `np.multiply(a, b)`    | `a * b`                               | `[10 40 90]`   |
| Division         | `/`    | `np.divide(a, b)`      | `a / b`                               | `[10. 10. 10.]`|
| Floor Division   | `//`   | `np.floor_divide(a, b)`| `a // b`                              | `[10 10 10]`   |
| Modulus          | `%`    | `np.mod(a, b)`         | `a % b`                               | `[0 0 0]`      |
| Power            | `**`   | `np.power(a, b)`       | `a ** b`                              | `[10 400 27000]`|


In [ ]:
arr1 = np.array([10,20,30])

print(arr1 + 3)
print()
print(np.add(arr1,3))

[13 23 33]

[13 23 33]


In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

print(arr1 + arr2)
print()
print(np.add(arr1,arr2))

[[ 8 10 12]
 [14 16 18]]

[[ 8 10 12]
 [14 16 18]]


In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

print(arr1 - arr2)
print()
print(np.subtract(arr1,arr2))

[[-6 -6 -6]
 [-6 -6 -6]]

[[-6 -6 -6]
 [-6 -6 -6]]


In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

print(arr1 * arr2)
print()
print(np.multiply(arr1,arr2))


[[ 7 16 27]
 [40 55 72]]

[[ 7 16 27]
 [40 55 72]]


In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

print(arr1 / arr2)
print()
print(np.divide(arr1,arr2))


[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

print(arr1 // arr2)
print()
print(np.floor_divide(arr1,arr2))


[[0 0 0]
 [0 0 0]]

[[0 0 0]
 [0 0 0]]


In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

print(arr1 % arr2)
print()
print(np.mod(arr1,arr2))

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]]


In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

print(arr1 ** arr2)
print()
print(np.power(arr1,arr2))

[[         1        256      19683]
 [   1048576   48828125 2176782336]]

[[         1        256      19683]
 [   1048576   48828125 2176782336]]


In [ ]:
#reciprocal
arr1 = np.array([1,2,3])
print(np.reciprocal(arr1))

[1 0 0]


#Basic Airthmetic functions

min

max

argmin

sqrt

sin

cos

cumsum

| Function Name         | Syntax / Usage      | Description                                      | Example                                   | Output            |
|-----------------------|---------------------|--------------------------------------------------|-------------------------------------------|-------------------|
| `abs()` / `absolute()`| `np.abs(a)`         | Absolute value of each element                   | `np.abs([-1, -2, 3])`                      | `[1 2 3]`         |
| `sqrt()`              | `np.sqrt(a)`        | Square root of each element                      | `np.sqrt([1, 4, 9])`                       | `[1. 2. 3.]`      |
| `exp()`               | `np.exp(a)`         | Exponential (e^x) of each element                | `np.exp([1, 2])`                           | `[2.718 7.389]`   |
| `log()`               | `np.log(a)`         | Natural logarithm (base e)                       | `np.log([1, np.e])`                        | `[0. 1.]`         |
| `log10()`             | `np.log10(a)`       | Base-10 logarithm of each element                | `np.log10([1, 10, 100])`                  | `[0. 1. 2.]`      |
| `log2()`              | `np.log2(a)`        | Base-2 logarithm of each element                 | `np.log2([1, 2, 4])`                       | `[0. 1. 2.]`      |
| `max()`               | `np.max(a)`         | Maximum element in the array                     | `np.max([4, 7, 2])`                        | `7`               |
| `min()`               | `np.min(a)`         | Minimum element in the array                     | `np.min([4, 7, 2])`                        | `2`               |
| `sum()`               | `np.sum(a)`         | Sum of all elements                              | `np.sum([1, 2, 3])`                        | `6`               |
| `mean()`              | `np.mean(a)`        | Mean (average) of the array                      | `np.mean([1, 2, 3])`                       | `2.0`             |
| `median()`            | `np.median(a)`      | Median of the array                              | `np.median([1, 3, 2])`                     | `2.0`             |
| `std()`               | `np.std(a)`         | Standard deviation                               | `np.std([1, 2, 3])`                        | `0.816`           |
| `var()`               | `np.var(a)`         | Variance                                         | `np.var([1, 2, 3])`                        | `0.666...`        |
| `round()`             | `np.round(a, n)`    | Round to `n` decimals                            | `np.round([1.234, 5.678], 1)`              | `[1.2 5.7]`       |
| `floor()`             | `np.floor(a)`       | Floor (round down) each element                  | `np.floor([1.9, 2.1])`                     | `[1. 2.]`         |
| `ceil()`              | `np.ceil(a)`        | Ceil (round up) each element                     | `np.ceil([1.2, 2.8])`                      | `[2. 3.]`         |


In [ ]:
arr_min = np.array([4,7,2])
print("Minimum value : ",np.min(arr_min))
print("Maximum value : ",np.max(arr_min))
print("Minimum value index : ",np.argmin(arr_min)) # shows index number
print("Maximum value index : ",np.argmax(arr_min))  # shows index number

Minimum value :  2
Maximum value :  7
Minimum value index :  2
Maximum value index :  1


In [ ]:
var1 = np.array([[1,2,3,4,5],[11,20,30,55,40]])
#axis = 0  work accordingly column
#axis = 1 work accordingly rowwise
print(np.min(var1,axis=1))
print(np.max(var1,axis=1))

[ 1 11]
[ 5 55]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(np.sin(arr))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(np.cos(arr))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [ ]:
arr = np.array([0,1, 2, 3, 4, 5])
print(np.cumsum(arr))

[ 0  1  3  6 10 15]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(np.cumprod(arr))

[  1   2   6  24 120]


#Broadcasting numpy arrays

✅ Broadcasting in NumPy Arrays
Broadcasting is a powerful feature in NumPy that allows arithmetic operations on arrays of different shapes and sizes — without explicitly reshaping or looping.

🔹 Why Broadcasting?
To perform operations between arrays of different shapes, NumPy automatically expands one array to match the shape of the other, without actually copying data.

🔸 Broadcasting Rules
For two arrays to be broadcastable, the shapes must be compatible using the following rules:

If the dimensions are not equal, prepend 1s to the shape of the smaller array.

Dimensions are compatible if:

They are equal, or

One of them is 1



In [ ]:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
print("Shape : ",arr1.shape)
print()
print(arr1)
print()
arr2 = np.array([7,8,9])
print("Shape : ",arr2.shape)
print()
print(arr2)
print()
print(arr1 + arr2)

Shape :  (2, 3)

[[1 2 3]
 [4 5 6]]

Shape :  (3,)

[7 8 9]

[[ 8 10 12]
 [11 13 15]]


In [ ]:
x = np.array([[1],[2]])
print(x.shape)
print()

y = np.array([[1,2,3],[1,2,3]])
print(y.shape)
print()

print(x + y)

(2, 1)

(2, 3)

[[2 3 4]
 [3 4 5]]


#Indexing Numpy Arrays


Array indexing in NumPy refers to the method of accessing specific elements or subsets of data within an array. This feature allows us to retrieve, modify and manipulate data at specific positions or ranges helps in making it easier to work with large datasets.


1. Accessing Elements in 1D Arrays
A 1D NumPy array is a sequence of values with positions called indices which starts at 0. We access elements by using these indices in square brackets like arr[0] for the first element. Negative indices count from the end so arr[-1] gives the last element.

In [ ]:
import numpy as np

var =  np.array([1,2,3,4,5,6])
#positive indexing
print(var[2])
#negative indexing
print(var[-1])

3
6


2. Accessing Elements in Multidimensional Arrays
In this we will see how to access elements in both 2D and 3D arrays using specific indices.

2D Arrays: We can access elements by specifying both row and column indices like matrix[row, column].

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print()
print(arr1.ndim)
print()
print(arr1[1,2])

[[1 2 3]
 [4 5 6]]

2

6


In [ ]:
arr1 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr1)
print()
print(arr1.ndim)
print()
print(arr1[1,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

3

12


3. Slicing Arrays
It allows us to extract a range of elements using the format start:stop:step. This can be done for both 1D and multidimensional arrays which allows us to select ranges of elements or submatrices easily.

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5])

print(arr[1:4])

print(arr[2:])

print(arr[:4])

print(arr[-3:-1])

print(arr[1:5:2])

[1 2 3]
[2 3 4 5]
[0 1 2 3]
[3 4]
[1 3]


In [ ]:
#2d and 3d array slicing

arr1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr1[1, 1:4])
print()
arr2 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr2[0, 1, 1:3])

[7 8 9]
[5 6]


4. Boolean Indexing
It allows us to filter elements from an array based on a condition and returns only those that meet it. We create a boolean array from a condition and use it to select elements and can combine conditions with logical operators.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[arr > 2])

print()
print(arr[arr % 2 == 0])


[3 4 5]

[2 4]


5. What is Fancy Indexing?
Fancy indexing (also called advanced indexing) allows you to:

Access multiple elements at once

Use a list or NumPy array of indices

Select non-contiguous elements (they don’t have to be next to each other)



In [ ]:
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
print(arr[indices])

[10 30 50]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = [0, 2 ]
print(arr[indices])

[[1 2 3]
 [7 8 9]]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.array([[0, 1], [1, 2]])
print(arr[indices])

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
indices = np.array([True, False, True, False, True])
print(arr[indices])

[10 30 50]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.array([[True, False, True], [False, True, False], [True, False, True]])
print(arr[indices])

[1 3 5 7 9]


In [ ]:
#3d array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
indices = np.array([[[True, False, True], [False, True, False]], [[True, False, True], [False, True, False]]])
print(arr[indices])

[ 1  3  5  7  9 11]


#Iterating Numpy Arrays

In [ ]:
arr1 = np.array([1,2,3,4,5])
#using for loop
for i in arr1:
  print(i, end=" ")

1 2 3 4 5 

In [ ]:
#2d array
arr2 = np.array([[1,2,3],[4,5,6]])

for i in arr2:
  print(i)

print()

for i in arr2:
  for j in i:
    print(j, end=" ")


[1 2 3]
[4 5 6]

1 2 3 4 5 6 

In [ ]:
#multidimensional array
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for i in arr3:
  print(i)

print()

for i in arr3:
  for j in i:
    for k in j:
      print(k, end=" ")

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]

1 2 3 4 5 6 7 8 9 10 11 12 

In [ ]:
#multidimensional array
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

#nditer function used to iteration
for i in np.nditer(arr3):
  print(i, end=" ")

print()

for i in np.nditer(arr3, flags=['buffered'], op_dtypes=['S']):
  print(i)

print()

#accessing the indexing number with elements
for index,data in np.ndenumerate(arr3):
  print(index," = ",data)

print()



1 2 3 4 5 6 7 8 9 10 11 12 
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')
np.bytes_(b'7')
np.bytes_(b'8')
np.bytes_(b'9')
np.bytes_(b'10')
np.bytes_(b'11')
np.bytes_(b'12')

(0, 0, 0)  =  1
(0, 0, 1)  =  2
(0, 0, 2)  =  3
(0, 1, 0)  =  4
(0, 1, 1)  =  5
(0, 1, 2)  =  6
(1, 0, 0)  =  7
(1, 0, 1)  =  8
(1, 0, 2)  =  9
(1, 1, 0)  =  10
(1, 1, 1)  =  11
(1, 1, 2)  =  12



#Copy vs View in numpy array

✅ Difference Between copy() and view() in NumPy

🔹 copy():
Creates a completely new and independent array.

Changes made to the copied array do not affect the original array.

Allocates new memory space for the copied data.

Used when you want to preserve the original array.

copy().base returns None, indicating no shared memory.

🔹 view():
Creates a new array object, but the data is shared with the original.

Changes made to the view will reflect in the original array.

Does not allocate new memory for the data — only a new view object.

Useful for efficient memory usage.

view().base returns a reference to the original array.


In [ ]:
var = np.array([1,2,3,4])

co = var.copy()

print("Original Array : ",var)
print()
print("Copy Array : ",co)

co[1] = 100
var[2] = 500
print()
print("Original Array : ",var)
print()
print("Copy Array : ",co)

print()
print("Original Array Reference : ",id(var))
print()
print("Copy Array Reference : ",id(co))


Original Array :  [1 2 3 4]

Copy Array :  [1 2 3 4]

Original Array :  [  1   2 500   4]

Copy Array :  [  1 100   3   4]

Original Array Reference :  133830551370032

Copy Array Reference :  133830551449744


In [ ]:
x  = np.array([1,2,3,4])

vi = x.view()
print("Array : ",x)
print()
print("View Array : ",vi)

vi[1] = 100
x[3] = 200

print()
print("Array : ",x)
print()
print("View Array : ",vi)

print()
print("Original Array Reference : ",id(x))
print()
print("View Array Reference : ",id(vi))


Array :  [1 2 3 4]

View Array :  [1 2 3 4]

Array :  [  1 100   3 200]

View Array :  [  1 100   3 200]

Original Array Reference :  133830551665520

View Array Reference :  133830551452912


#Join And Split Functions in numpy array

🔹 Join Functions (Combining Arrays)
Joining means combining two or more arrays into one.

NumPy provides multiple functions to join arrays along different axes.

Arrays must be of compatible shapes for the axis along which they are joined.

Common Join Functions:

np.concatenate() – joins along an existing axis.

np.stack() – joins along a new axis (adds dimension).

np.hstack() – joins arrays horizontally (columns).

np.vstack() – joins arrays vertically (rows).

np.dstack() – joins arrays along the depth (3rd axis).

🔹 Split Functions (Dividing Arrays)
Splitting means breaking an array into smaller sub-arrays.

NumPy provides various split functions for equal and unequal parts.

The number of splits must evenly divide the axis (except array_split()).

Common Split Functions:

np.split() – splits into equal parts along a specified axis.

np.array_split() – allows unequal splits.

np.hsplit() – splits horizontally (columns).

np.vstack() – splits vertically (rows).

np.dsplit() – splits along the depth (3rd axis).


| Category | Function         | Description                                  | Axis Affected     |
|----------|------------------|----------------------------------------------|-------------------|
| Join     | `concatenate()`  | Join arrays along an existing axis           | Any existing axis |
| Join     | `stack()`        | Join arrays along a new axis                 | New axis          |
| Join     | `hstack()`       | Horizontal stack (side by side)              | Axis = 1          |
| Join     | `vstack()`       | Vertical stack (top-bottom)                  | Axis = 0          |
| Join     | `dstack()`       | Stack along depth (3rd axis)                 | Axis = 2          |
| Split    | `split()`        | Split into equal parts                       | Any existing axis |
| Split    | `array_split()`  | Split into unequal parts                     | Any axis          |
| Split    | `hsplit()`       | Horizontal split (by columns)                | Axis = 1          |
| Split    | `vsplit()`       | Vertical split (by rows)                     | Axis = 0          |
| Split    | `dsplit()`       | Split along depth (3D arrays only)           | Axis = 2          |




In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr = np.concatenate((arr1,arr2))
print(arr)


[1 2 3 4 5 6 7 8]


In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

arr = np.concatenate((arr1,arr2),axis=1)
print(arr)
print()
arr = np.concatenate((arr1,arr2),axis=0)
print(arr)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#stack function
ar1  = np.array([1,2,3,4])
ar2 = np.array([5,6,7,8])

ar3 = np.stack((ar1,ar2), axis=1)
print(ar3)
print()
ar3 = np.stack((ar1,ar2), axis=0)
print(ar3)


[[1 5]
 [2 6]
 [3 7]
 [4 8]]

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#hstack function -it works with row
ar1  = np.array([1,2,3,4])
ar2 = np.array([5,6,7,8])

ar3 = np.hstack((ar1,ar2))
print(ar3)


[1 2 3 4 5 6 7 8]


In [ ]:
#vstack function - it works with column
ar1  = np.array([1,2,3,4])
ar2 = np.array([5,6,7,8])

ar3 = np.vstack((ar1,ar2))
print(ar3)


[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#dstack - it works with height
ar1  = np.array([1,2,3,4])
ar2 = np.array([5,6,7,8])

ar3 = np.dstack((ar1,ar2))
print(ar3)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [ ]:
#split
ar1 = np.array([1,2,3,4,5,6])

ar2 = np.split(ar1,2)
print(ar2)
print()

#array_split(array_name , partition_number_of_array)
ar1 = np.array([1,2,3,4,5,6])

ar2 = np.array_split(ar1,2)
print(ar2)

print()
ar2 = np.array_split(ar1,4)
print(ar2)

print()
ar2 = np.array_split(ar1,3)
print(ar2)

[array([1, 2, 3]), array([4, 5, 6])]

[array([1, 2, 3]), array([4, 5, 6])]

[array([1, 2]), array([3, 4]), array([5]), array([6])]

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
ar1 = np.array([[1,2,3],[4,5,6]])

ar2 = np.array_split(ar1,2)
print(ar2)
print()

ar2 = np.array_split(ar1,3)
print(ar2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int64)]


In [ ]:
#hsplit
ar1 = np.array([[1,2,3],[4,5,6]])

ar2 = np.hsplit(ar1,3)
print(ar2)
print()
#vsplit
ar2 = np.vsplit(ar1,2)
print(ar2)
print()



[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]

[array([[1, 2, 3]]), array([[4, 5, 6]])]



# Numpy Arrays Functions Search , Sort , Search Sorted , Filter

In [85]:
import numpy as np

#search
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr == 4)  # it gives the index positions of elements
print(x)
print()
y = np.where((arr%2)==0)
print(y)

(array([3, 5, 6]),)

(array([1, 3, 5, 6]),)


In [89]:
#search sorted -> perform binary search
ar = np.array([1,2,3,45,56,67,89])
x = np.searchsorted(ar , 5)
print(x)
print()
x = np.searchsorted(ar , 56 , side='right')
print(x)
print()
x = np.searchsorted(ar , [5,56,67])
print(x)

3

5

[3 4 5]


In [93]:
# sort
a = np.array([12,1,2,34,5,3,80,70,45,43,67])
print("Original Array  : ",a)
print()
sort_array = np.sort(a)
print("Sorted Array  : ",sort_array)

#2d array
print()
a = np.array([[12,1,2,34],[5,3,11,80],[70,45,43,67]])
print("Original Array  : \n",a)
print()
sort_array = np.sort(a)
print("Sorted Array  : \n",sort_array)

#alphabet array
alphabet_arr = np.array(['z','b','a','d','e','c'])
print()
print("Original Array  : ",alphabet_arr)
print()
sort_array = np.sort(alphabet_arr)
print("Sorted Array  : ",sort_array)

#string array
str_array = np.array(['pratik','dipak','abhi','babblu'])
print()
print("Original Array  : ",str_array)
print()
sort_array = np.sort(str_array)
print("Sorted Array  : ",sort_array)


Original Array  :  [12  1  2 34  5  3 80 70 45 43 67]

Sorted Array  :  [ 1  2  3  5 12 34 43 45 67 70 80]

Original Array  : 
 [[12  1  2 34]
 [ 5  3 11 80]
 [70 45 43 67]]

Sorted Array  : 
 [[ 1  2 12 34]
 [ 3  5 11 80]
 [43 45 67 70]]

Original Array  :  ['z' 'b' 'a' 'd' 'e' 'c']

Sorted Array  :  ['a' 'b' 'c' 'd' 'e' 'z']

Original Array  :  ['pratik' 'dipak' 'abhi' 'babblu']

Sorted Array  :  ['abhi' 'babblu' 'dipak' 'pratik']


In [99]:
#filter

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

filter_newarr = arr[x]

print(filter_newarr)

#another eaxpmle with condition
filter_arr = arr > 42

newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[41 43]
[False False  True  True]
[43 44]


# Shuffle , Unique , Resize , Flatten , Ravel Functions

# 1. np.random.shuffle()

Purpose: Randomly shuffles the elements of an array in-place (only along the first axis).

✅ Theory Points:
Modifies the original array.

Does not return anything (returns None).

For 2D arrays: only rows are shuffled, not the elements within rows.

In [103]:
arr1  = np.array([1,2,3,4,5])
np.random.shuffle(arr1)
print(arr1)

[1 5 4 2 3]


#2. np.unique()

Purpose: Returns sorted unique elements from an array.

✅ Theory Points:
Does not modify the original array.

Returns a new array of unique sorted values.

You can also get counts, indices, or inverse using parameters.

In [106]:
a = np.array([1, 2, 2, 3, 4, 4])
unique = np.unique(a)
print(unique)  # Output: [1 2 3 4]
print()
#index position
unique, indices = np.unique(a, return_index=True)
print(unique)  # Output: [1 2 3 4]
print(indices)  # Output: [0 1 3 5]
print()
#count
unique, counts = np.unique(a, return_counts=True)
print(unique)  # Output: [1 2 3 4]
print(counts)  # Output: [1 2 1 2]


[1 2 3 4]

[1 2 3 4]
[0 1 3 4]

[1 2 3 4]
[1 2 1 2]


# 3. np.resize()

Purpose: Returns a new array with the given shape. Fills extra space by repeating data if needed.

✅ Theory Points:
Different from reshape(), it can increase or decrease size.

Returns a new resized array.

In [111]:
arr = np.array([1, 2, 3, 4, 5, 6])
resized = np.resize(arr, (3, 2))
print(resized)
print()
#1d again
resized = np.resize(arr, (6))
print(resized)
#another way
print()
resized = np.resize(arr, (3, 3))
print(resized)

[[1 2]
 [3 4]
 [5 6]]

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]
 [1 2 3]]


 # 4. flatten()

Purpose: Converts any array into a 1D copy.

✅ Theory Points:

Returns a new 1D array.

Original array remains unchanged.

Default row-major (C-style) flattening.

In [113]:
a = np.array([[1, 2], [3, 4]])
flat = a.flatten()
print(flat)  # Output: [1 2 3 4]

print()

#pass the order
flat = a.flatten(order='F')
print(flat)  # Output: [1 3 2 4]

print()


[1 2 3 4]

[1 3 2 4]


# 5. ravel()

Purpose: Returns a flattened view of the array (whenever possible).

✅ Theory Points:

Faster and uses less memory than flatten().

Returns a view if possible, else a copy.

Original array may change if you modify the raveled array.

In [115]:
a = np.array([[1, 2], [3, 4]])
r = a.ravel()
print(r)  # Output: [1 2 3 4]

print()
#pass the order
r = a.ravel(order='F')
print(r)  # Output: [1 3 2 4]

print()


[1 2 3 4]

[1 3 2 4]



# Insert And Delete functions

✅ NumPy insert() and delete() Functions

These functions help in modifying array structure by adding or removing elements.

🔹 np.insert()

📌 Purpose:
Inserts values into an array at specified indices.

✅ Theory Points:

Returns a new array (original is unchanged).

Can insert a single value or multiple values.

Works with 1D and multidimensional arrays.

# Syntax:
np.insert(arr, index, value, axis=None)

In [129]:
arr = np.array([1, 2, 3, 4, 5])
new_arr = np.insert(arr, 2, 10)
print(new_arr)  # Output: [ 1  2 10  3  4  5]

print()
#insert multiple values
new_arr = np.insert(arr, (2, 4), [10, 20])
print(new_arr)  # Output: [ 1  2 10 20  3  4  5]

print()
#2d array
arr = np.array([[1, 2], [3, 4]])
new_arr = np.insert(arr, 1, [10, 20], axis=0)
print(new_arr)
print()

#2d array
arr = np.array([[1, 2], [3, 4]])
new_arr = np.insert(arr, 1, [10, 20], axis=1)
print(new_arr)
print()
#multi dimensional array
arr = np.array([[1, 2], [3, 4]])
new_arr = np.insert(arr, 1, [[10, 20], [30, 40]], axis=1)
print(new_arr)

#using append function
print()
arr = np.array([1, 2, 3, 4, 5])
new_arr = np.append(arr, [10, 20])
print(new_arr)

#2d array
print()
arr = np.array([[1, 2], [3, 4]])
new_arr = np.append(arr, [[10, 20]], axis=0)
print(new_arr)

#axis 1
print()
arr = np.array([[1, 2], [3, 4]])
new_arr = np.append(arr, [[10], [20]], axis=1)
print(new_arr)

[ 1  2 10  3  4  5]

[ 1  2 10  3  4 20  5]

[[ 1  2]
 [10 20]
 [ 3  4]]

[[ 1 10  2]
 [ 3 20  4]]

[[ 1 10 30  2]
 [ 3 20 40  4]]

[ 1  2  3  4  5 10 20]

[[ 1  2]
 [ 3  4]
 [10 20]]

[[ 1  2 10]
 [ 3  4 20]]


#🔹 np.delete()

📌 Purpose:
Deletes elements from an array at specified indices.

✅ Theory Points:

Returns a new array (original is unchanged).

Can delete single or multiple indices.

Can work along any axis in multi-dimensional arrays.

# Syntax:

np.delete(arr, index, axis=None)

In [132]:
#delete
arr = np.array([10,20,30,40,50,60,70])
new_arr = np.delete(arr, [1,4])
print(new_arr)

#2d array
print()
arr = np.array([[1, 2], [3, 4]])
new_arr = np.delete(arr, 1, axis=0)
print(new_arr)

# 3d array
print()
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
new_arr = np.delete(arr, 1, axis=2)
print(new_arr)

[10 30 40 60 70]

[[1 2]]

[[[1]
  [3]]

 [[5]
  [7]]]


# Matrix in numpy arrays

✅ Matrix in NumPy

A matrix is a rectangular array of numbers arranged in rows and columns. In NumPy, matrices are represented using 2D arrays.

🔹 What is a Matrix in NumPy?
NumPy represents matrices as 2-dimensional arrays using np.array().

Shape of a matrix: (rows, columns).

NumPy also has a special np.matrix class, but it’s not recommended — use np.array for flexibility.



In [133]:
matrix  = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print()
print(type(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

<class 'numpy.matrix'>


In [134]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.matrix([[7,8,9],[10,11,12]])
print(type(arr1))
print(type(arr2))

<class 'numpy.ndarray'>
<class 'numpy.matrix'>


# 🔹 Common Matrix Functions in NumPy

| Function Name     | Syntax / Usage              | Description                             | Example                               | Output                           |
|------------------|-----------------------------|-----------------------------------------|---------------------------------------|----------------------------------|
| array()          | np.array()                  | Create matrix                           | np.array([[1, 2], [3, 4]])            | [[1 2] [3 4]]                    |
| zeros()          | np.zeros((m, n))            | m×n matrix of all 0s                    | np.zeros((2, 3))                      | [[0. 0. 0.], [0. 0. 0.]]         |
| ones()           | np.ones((m, n))             | m×n matrix of all 1s                    | np.ones((2, 3))                       | [[1. 1. 1.], [1. 1. 1.]]         |
| eye()            | np.eye(n)                   | Identity matrix of size n×n            | np.eye(3)                             | [[1. 0. 0.], [0. 1. 0.], [0. 0. 1.]] |
| transpose()      | A.T or matrix.T             | Transpose matrix (rows ↔ columns)       | np.array([[1, 2], [3, 4]]).T          | [[1 3], [2 4]]                   |
| reshape()        | np.reshape(mat, shape)      | Reshape matrix to a different shape     | np.reshape([[1,2],[3,4]], (1,4))      | [[1 2 3 4]]                      |






# 🔹 Matrix Operations

| Operation Name       | Syntax / Usage                 | Description                           | Example                                 | Output                         |
|----------------------|-------------------------------|---------------------------------------|-----------------------------------------|--------------------------------|
| Matrix addition      | A + B                         | Element-wise addition                 | [[1,2],[3,4]] + [[5,6],[7,8]]           | [[6 8], [10 12]]               |
| Matrix subtraction   | A - B                         | Element-wise subtraction              | [[5,6],[7,8]] - [[1,2],[3,4]]           | [[4 4], [4 4]]                 |
| Matrix multiplication| np.dot(A, B) or A @ B         | Dot product (matrix multiplication)   | np.dot([[1,2],[3,4]], [[5,6],[7,8]])    | [[19 22], [43 50]]             |
| Element-wise multiply| A * B                         | Multiplies corresponding elements     | [[1,2],[3,4]] * [[2,2],[2,2]]           | [[2 4], [6 8]]                 |
| Transpose            | A.T                           | Transpose rows and columns            | [[1,2,3],[4,5,6]].T                     | [[1 4], [2 5], [3 6]]          |
| Inverse              | np.linalg.inv(A)              | Inverse of a square matrix            | np.linalg.inv([[1,2],[3,4]])           | [[-2. 1.], [1.5 -0.5]]         |
| Determinant          | np.linalg.det(A)              | Scalar determinant                    | np.linalg.det([[1,2],[3,4]])           | -2.0000000000000004            |
| Rank                 | np.linalg.matrix_rank(A)      | Finds rank of matrix                  | np.linalg.matrix_rank([[1,2],[3,6]])   | 1                              |


In [135]:
#addition in array
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = a+b
print(c)

print()
#addition in matrix
a = np.matrix([[1,2],[3,4]])
b = np.matrix([[5,6],[7,8]])
c = a+b
print(c)


[[ 6  8]
 [10 12]]

[[ 6  8]
 [10 12]]


In [136]:
#subtraction in array
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = a-b
print(c)

print()
#subtraction in matrix
a = np.matrix([[1,2],[3,4]])
b = np.matrix([[5,6],[7,8]])
c = a-b
print(c)

[[-4 -4]
 [-4 -4]]

[[-4 -4]
 [-4 -4]]


In [138]:
#multiplication in array
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = a*b
print(c)

print()
#multiplication in matrix
a = np.matrix([[1,2],[3,4]])
b = np.matrix([[5,6],[7,8]])
c = a*b
print(c)

#dot
print()
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.dot(a,b)
print(c)

[[ 5 12]
 [21 32]]

[[19 22]
 [43 50]]

[[19 22]
 [43 50]]


In [139]:
#transpose
a = np.array([[1,2],[3,4]])
print(a)
print()
print(a.T)

#another way
print()
a = np.matrix([[1,2],[3,4]])
print(a)
print()
print(a.T)

#another way
print()
a = np.array([[1,2],[3,4]])
print(a)
print()
print(np.transpose(a))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [140]:
#swapaxes
a = np.array([[1,2],[3,4]])
print(a)
print()
print(np.swapaxes(a,0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [142]:
#inverse
a = np.array([[1,2],[3,4]])
print(a)
print()
print(np.linalg.inv(a))

#another way
print()
a = np.matrix([[1,2],[3,4]])
print(a)
print()
print(a.I)

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [144]:
#determinant
a = np.array([[1,2],[3,4]])
print(a)
print()
print(np.linalg.det(a))

#another way
print()
a = np.matrix([[1,2],[3,4]])
print(a)
print()
print(np.linalg.det(a))

[[1 2]
 [3 4]]

-2.0000000000000004

[[1 2]
 [3 4]]

-2.0000000000000004


In [145]:
#power
a = np.array([[1,2],[3,4]])
print(a)
print()
print(np.linalg.matrix_power(a,2))

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]
